export const channelDataMock = {
    "id": "35357",
    "number": "3",
    "name": "CANAL 3 GT",
    "hd": false,
    "image": "https://clarovideocdn8.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/SS/CANAL3GT_t-290x163.png",
    "group_id": "889020",
    "liveref": "sv.CANAL3NACIONAL",
    "epg_url": "TV",
    "provider_metadata_id": 2,
    "provider_metadata_name": "NAGRA",
    "group": {
        "common": {
            "id": "889020",
            "title": "CANAL 3 GT",
            "title_episode": null,
            "title_uri": "CANAL-3-GT",
            "title_original": "CANAL 3 GT",
            "description": "CANAL 3 GT IPTV GUATEMALA",
            "description_large": "CANAL 3 GT",
            "short_description": null,
            "image_large": "https://clarovideocdn2.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/SS/CANAL3GTWHORIZONTAL.jpg?size=675x380",
            "image_medium": "https://clarovideocdn0.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/SS/CANAL3GTWVERTICAL.jpg?size=200x300",
            "image_small": "https://clarovideocdn2.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/SS/CANAL3GTWHORIZONTAL.jpg?size=290x163",
            "image_still": null,
            "image_background": "https://clarovideocdn2.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/CLEAN/CANAL3GT_e-1280x720.jpg",
            "url_imagen_t1": "https://clarovideocdn3.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/CLEAN/CANAL3GTWVERTICAL.jpg?size=200x300",
            "url_imagen_t2": "https://clarovideocdn5.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/CLEAN/CANAL3GTWHORIZONTAL.jpg?size=290x163",
            "image_base_horizontal": "https://clarovideocdn9.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/SS/CANAL3GTWHORIZONTAL.jpg",
            "image_base_vertical": "https://clarovideocdn7.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/SS/CANAL3GTWVERTICAL.jpg",
            "image_base_square": "https://clarovideocdn7.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/SS/CANAL3GTWCUADRADO.jpg",
            "image_clean_horizontal": "https://clarovideocdn2.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/CLEAN/CANAL3GTWHORIZONTAL.jpg",
            "image_clean_vertical": "https://clarovideocdn0.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/CLEAN/CANAL3GTWVERTICAL.jpg",
            "image_clean_square": "https://clarovideocdn0.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/CLEAN/CANAL3GTWCUADRADO.jpg",
            "image_sprites": "https://clarovideocdn3.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/SPRITES/CANAL3GT-SPRITEBAR.jpg",
            "image_frames": "https://clarovideocdn9.clarovideo.net/CVPERU/PELICULAS/CANAL3GT/EXPORTACION_WEB/SPRITES/CANAL3GT-00h-00m-00s-00f.jpg",
            "image_trickplay": "",
            "image_external": null,
            "duration": null,
            "date": "15/07/2020",
            "year": null,
            "preview": "false",
            "season_number": null,
            "episode_number": null,
            "format_types": "susc",
            "live_enabled": "1",
            "live_type": "1",
            "live_ref": "sv.CANAL3NACIONAL",
            "timeshift": "4000",
            "votes_average": 4,
            "rating_code": "G",
            "proveedor_name": "CLARO VIDEO PERU",
            "proveedor_code": "cvperu",
            "encoder_tecnology": {
                "id": "3",
                "desc": "HARMONIC_VOS"
            },
            "recorder_technology": {
                "id": "4",
                "desc": "HARMONIC_VOS"
            },
            "resource_name": null,
            "rollingcreditstime": null,
            "rollingcreditstimedb": null,
            "is_series": false,
            "channel_number": "3"
        }
    },
    "events": [
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald",
            "description": `
                Las aventuras del Pato Donald es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/12 20:02:56",
            "date_end": "2021/08/12 21:02:56",
            "unix_begin": 1628820176,
            "unix_end": 1628823776,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 1,
            "ext_series_id": null,
            "ext_season_id": 1,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 2",
            "description": `
                Las aventuras del Pato Donald 2 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/12 21:02:56",
            "date_end": "2021/08/12 22:02:56",
            "unix_begin": 1628823776,
            "unix_end": 1628827376,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 2,
            "ext_series_id": null,
            "ext_season_id": 2,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald con Goofy",
            "description": `
                Las aventuras del Pato Donald y Goofy es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/12 22:02:56",
            "date_end": "2021/08/12 23:02:56",
            "unix_begin": 1628827376,
            "unix_end": 1628830976,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 1,
            "ext_series_id": null,
            "ext_season_id": 1,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald y Minnie",
            "description": `
                Las aventuras del Pato Donald con Minnie es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/12 23:02:56",
            "date_end": "2021/08/13 00:02:56",
            "unix_begin": 1628830976,
            "unix_end": 1628834576,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 1,
            "ext_series_id": null,
            "ext_season_id": 1,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 3",
            "description": `
                Las aventuras del Pato Donald 3 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 00:02:56",
            "date_end": "2021/08/13 01:02:56",
            "unix_begin": 1628834576,
            "unix_end": 1628838176,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 3,
            "ext_series_id": null,
            "ext_season_id": 3,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 4",
            "description": `
                Las aventuras del Pato Donald 4 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 01:02:56",
            "date_end": "2021/08/13 02:02:56",
            "unix_begin": 1628838176,
            "unix_end": 1628841776,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 4,
            "ext_series_id": null,
            "ext_season_id": 4,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 5",
            "description": `
                Las aventuras del Pato Donald 5 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 02:02:56",
            "date_end": "2021/08/13 03:02:56",
            "unix_begin": 1628841776,
            "unix_end": 1628845376,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 5,
            "ext_series_id": null,
            "ext_season_id": 5,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 6",
            "description": `
                Las aventuras del Pato Donald 6 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 03:02:56",
            "date_end": "2021/08/13 04:02:56",
            "unix_begin": 1628845376,
            "unix_end": 1628848976,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 6,
            "ext_series_id": null,
            "ext_season_id": 6,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 7",
            "description": `
                Las aventuras del Pato Donald 7 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 04:02:56",
            "date_end": "2021/08/13 05:02:56",
            "unix_begin": 1628848976,
            "unix_end": 1628852576,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 7,
            "ext_series_id": null,
            "ext_season_id": 7,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 8",
            "description": `
                Las aventuras del Pato Donald 8 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 05:02:56",
            "date_end": "2021/08/13 06:02:56",
            "unix_begin": 1628852576,
            "unix_end": 1628856176,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 8,
            "ext_series_id": null,
            "ext_season_id": 8,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 9",
            "description": `
                Las aventuras del Pato Donald 9 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 06:02:56",
            "date_end": "2021/08/13 07:02:56",
            "unix_begin": 1628856176,
            "unix_end": 1628859776,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 9,
            "ext_series_id": null,
            "ext_season_id": 9,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 10",
            "description": `
                Las aventuras del Pato Donald 10 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 07:02:56",
            "date_end": "2021/08/13 08:02:56",
            "unix_begin": 1628859776,
            "unix_end": 1628863376,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 10,
            "ext_series_id": null,
            "ext_season_id": 10,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 11",
            "description": `
                Las aventuras del Pato Donald 11 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 08:02:56",
            "date_end": "2021/08/13 09:02:56",
            "unix_begin": 1628863376,
            "unix_end": 1628866976,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 11,
            "ext_series_id": null,
            "ext_season_id": 11,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 12",
            "description": `
                Las aventuras del Pato Donald 12 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 09:02:56",
            "date_end": "2021/08/13 10:02:56",
            "unix_begin": 1628866976,
            "unix_end": 1628870576,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 12,
            "ext_series_id": null,
            "ext_season_id": 12,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 13",
            "description": `
                Las aventuras del Pato Donald 13 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 10:02:56",
            "date_end": "2021/08/13 11:02:56",
            "unix_begin": 1628870576,
            "unix_end": 1628874176,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 13,
            "ext_series_id": null,
            "ext_season_id": 13,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 14",
            "description": `
                Las aventuras del Pato Donald 14 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 11:02:56",
            "date_end": "2021/08/13 12:02:56",
            "unix_begin": 1628874176,
            "unix_end": 1628877776,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 14,
            "ext_series_id": null,
            "ext_season_id": 14,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 15",
            "description": `
                Las aventuras del Pato Donald 15 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 12:02:56",
            "date_end": "2021/08/13 13:02:56",
            "unix_begin": 1628877776,
            "unix_end": 1628881376,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 15,
            "ext_series_id": null,
            "ext_season_id": 15,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 16",
            "description": `
                Las aventuras del Pato Donald 16 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 13:02:56",
            "date_end": "2021/08/13 14:02:56",
            "unix_begin": 1628881376,
            "unix_end": 1628884976,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 16,
            "ext_series_id": null,
            "ext_season_id": 16,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 17",
            "description": `
                Las aventuras del Pato Donald 17 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 14:02:56",
            "date_end": "2021/08/13 15:02:56",
            "unix_begin": 1628884976,
            "unix_end": 1628888576,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 17,
            "ext_series_id": null,
            "ext_season_id": 17,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 18",
            "description": `
                Las aventuras del Pato Donald 18 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 15:02:56",
            "date_end": "2021/08/13 16:02:56",
            "unix_begin": 1628888576,
            "unix_end": 1628892176,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 18,
            "ext_series_id": null,
            "ext_season_id": 18,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 19",
            "description": `
                Las aventuras del Pato Donald 19 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 16:02:56",
            "date_end": "2021/08/13 17:02:56",
            "unix_begin": 1628892176,
            "unix_end": 1628895776,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 19,
            "ext_series_id": null,
            "ext_season_id": 19,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 20",
            "description": `
                Las aventuras del Pato Donald 20 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 17:02:56",
            "date_end": "2021/08/13 18:02:56",
            "unix_begin": 1628895776,
            "unix_end": 1628899376,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 20,
            "ext_series_id": null,
            "ext_season_id": 20,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 21",
            "description": `
                Las aventuras del Pato Donald 21 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 18:02:56",
            "date_end": "2021/08/13 19:02:56",
            "unix_begin": 1628899376,
            "unix_end": 1628902976,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 21,
            "ext_series_id": null,
            "ext_season_id": 21,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        },
        {
            "channel_id": "35357",
            "id": "1",
            "name": "Las aventuras del pato Donald 22",
            "description": `
                Las aventuras del Pato Donald 22 es una serie de cómics
                y dibujos animados que siguen las hilarantes y a menudo
                desafortunadas experiencias de Donald Duck, un pato temperamental
                y bienintencionado.
            `,
            "talent": null,
            "date_begin": "2021/08/13 19:02:56",
            "date_end": "2021/08/13 20:02:56",
            "unix_begin": 1628902976,
            "unix_end": 1628906576,
            "duration": "01:00:00",
            "language": null,
            "type": null,
            "group_id": null,
            "confirmado": null,
            "id_empleado": null,
            "tms_id": null,
            "event_alf_id": null,
            "ext_ncont_id": null,
            "ext_nevt_id": null,
            "ext_actors": null,
            "ext_director": null,
            "ext_year": null,
            "ext_country": null,
            "ext_original_name": null,
            "ext_ep_original_name": 22,
            "ext_series_id": null,
            "ext_season_id": 22,
            "ext_episode_id": null,
            "ext_language": null,
            "ext_serie_short_desc": null,
            "ext_serie_desc": null,
            "image_base_horizontal": "",
            "image_base_vertical": "",
            "image_base_square": "",
            "ext_eventimage_name": "",
            "ext_eventimage_name_base": "https://www.elespectador.com/resizer/kymz8Q6Di9ZZpACZuQpafyMhjv4=/968x645/filters:quality(60):format(jpeg)/arc-anglerfish-arc2-prod-elespectador.s3.amazonaws.com/public/RT45D3AEARDZRBK7LAWZD55CX4.jpg",
            "ext_catchup": null,
            "ext_startover": null,
            "ext_recordable": null,
            "parental_rating": null,
            "aud_stereo": null,
            "aud_dolby": null,
            "vid_black_and_white": null,
            "dvb_content": null,
            "user_content": null,
            "group_rel": null,
            "gmt": -6
        }
    ]
}